### ISSUE TITLE
stdbscan implementation

### ISSUE THREAD

**Issue by placidoneto** [GeoGuideProject/geoguide#26]
Implement the ST-DBSCAN for Geoguide, mouse-tracking implicit catch points
A: definition of time interval for cluster cration:  < 10s 
B: Intersection of cluster. Time interval (N) for creation of prefered regions : NxA
C: Save the intersection (by 2) from B.
D: Relation between the regions and the points in the dataset.

**Comment by TiagoLisboa** [comment]
Ops, I should not have closed at https://github.com/GeoGuideProject/geoguide/commit/c2feabf06574f76f3f41a35cc4df823c0a8c4896. It's just the implementation of ST-DBSCAN.
