### ISSUE TITLE
experiments for polygons

### ISSUE THREAD

**Issue by placidoneto** [GeoGuideProject/geoguide#27]
execute geoguide with stdbscan for 3 datasets
taxi
yelp
airbnb
execute with different inputs:
100
1000
2000
4000

**Comment by TiagoLisboa** [comment]
**UPDATE**
execute geoguide with stdbscan for 2 datasets
yelp
airbnb 
execute with different inputs:
100
1000
2000
4000
Make 20 experiments with 2 min for each dataset
Use 40 sec to intersect polygons
**Annotate:**
Nº clusters and related points;
Nº intersections and related points.

**Comment by TiagoLisboa** [comment]
I'll make the experiments in the yelp dataset with 100, 1000, and 2000 points.
